/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Xe03gc3LjyI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Archivo } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function dummy() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <LeafIcon className="h-6 w-6" />
          <span className="text-xl font-bold">Spotmykrishi</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Products
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Grow Your Garden with Spotmykrishi
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  Discover a wide range of high-quality plants, seeds, fertilizers, and contract laborers to help you
                  cultivate your dream garden.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-green-600 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-green-700 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-green-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-green-500 dark:text-gray-900 dark:hover:bg-green-400 dark:focus-visible:ring-green-300"
                  href="#"
                >
                  Shop Now
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-green-600 border-green-600 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-green-100 hover:text-green-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-green-950 disabled:pointer-events-none disabled:opacity-50 dark:border-green-500 dark:border-green-500 dark:bg-gray-950 dark:hover:bg-green-500 dark:hover:text-gray-50 dark:focus-visible:ring-green-300"
                  href="#"
                >
                  Learn More
                </Link>
              </div>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:aspect-square"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore Our Product Categories</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Browse our wide selection of high-quality plants, seeds, fertilizers, and contract laborers to meet
                  all your gardening needs.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              <div className="group grid gap-4">
                <img
                  alt="Plants"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full transition-all duration-300 group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-1">
                  <h3 className="text-lg font-bold">Plants</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Discover a wide variety of healthy, vibrant plants for your garden.
                  </p>
                </div>
              </div>
              <div className="group grid gap-4">
                <img
                  alt="Seeds"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full transition-all duration-300 group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-1">
                  <h3 className="text-lg font-bold">Seeds</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Explore our selection of high-quality seeds for your garden.
                  </p>
                </div>
              </div>
              <div className="group grid gap-4">
                <img
                  alt="Fertilizers"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full transition-all duration-300 group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-1">
                  <h3 className="text-lg font-bold">Fertilizers</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Find the perfect fertilizers to nourish your plants and garden.
                  </p>
                </div>
              </div>
              <div className="group grid gap-4">
                <img
                  alt="Contract Laborers"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full transition-all duration-300 group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-1">
                  <h3 className="text-lg font-bold">Contract Laborers</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Hire experienced contract laborers to assist with your gardening tasks.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Why Choose Spotmykrishi?</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Discover the unique features and benefits that make Spotmykrishi the best choice for your gardening
                  needs.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Wide Product Selection</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Browse our extensive collection of high-quality plants, seeds, fertilizers, and contract
                        laborers.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Expert Advice</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Receive personalized recommendations and guidance from our team of gardening experts.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Reliable Delivery</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Enjoy fast and reliable delivery of your gardening supplies, right to your doorstep.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <img
                alt="Features"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Customers Say</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Hear from our satisfied customers about their experiences with Spotmykrishi.
                </p>
              </div>
              <div className="divide-y rounded-lg border">
                <div className="grid w-full grid-cols-1 items-stretch justify-center divide-x md:grid-cols-2 lg:grid-cols-3">
                  <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                    <img
                      alt="Avatar"
                      className="aspect-square overflow-hidden rounded-full object-cover object-center"
                      height="80"
                      src="/placeholder.svg"
                      width="80"
                    />
                    <div className="space-y-1 text-center">
                      <p className="text-lg font-bold">John Doe</p>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        "Spotmykrishi has been a game-changer for my garden. The quality of their products and the
                        expert advice have been invaluable."
                      </p>
                    </div>
                  </div>
                  <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                    <img
                      alt="Avatar"
                      className="aspect-square overflow-hidden rounded-full object-cover object-center"
                      height="80"
                      src="/placeholder.svg"
                      width="80"
                    />
                    <div className="space-y-1 text-center">
                      <p className="text-lg font-bold">Jane Smith</p>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        "I've been using Spotmykrishi for all my gardening needs, and I'm consistently impressed by the
                        quality and variety of their products."
                      </p>
                    </div>
                  </div>
                  <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                    <img
                      alt="Avatar"
                      className="aspect-square overflow-hidden rounded-full object-cover object-center"
                      height="80"
                      src="/placeholder.svg"
                      width="80"
                    />
                    <div className="space-y-1 text-center">
                      <p className="text-lg font-bold">Michael Johnson</p>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        "Spotmykrishi has made my gardening experience so much easier and more enjoyable. I highly
                        recommend their services to anyone looking to improve their garden."
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-green-600 p-6 md:py-12 w-full text-gray-50">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
            <Link className="hover:underline" href="#">
              About Us
            </Link>
            <Link className="hover:underline" href="#">
              Our Team
            </Link>
            <Link className="hover:underline" href="#">
              Careers
            </Link>
            <Link className="hover:underline" href="#">
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
            <Link className="hover:underline" href="#">
              Plants
            </Link>
            <Link className="hover:underline" href="#">
              Seeds
            </Link>
            <Link className="hover:underline" href="#">
              Fertilizers
            </Link>
            <Link className="hover:underline" href="#">
              Contract Laborers
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link className="hover:underline" href="#">
              Blog
            </Link>
            <Link className="hover:underline" href="#">
              Community
            </Link>
            <Link className="hover:underline" href="#">
              Support
            </Link>
            <Link className="hover:underline" href="#">
              FAQs
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
            <Link className="hover:underline" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:underline" href="#">
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}
